/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Achivements(props) {
    const { nodes, materials } = useGLTF("/assets/achivements building (1).glb");
    return (
        <group {...props} dispose={null} position={[250, 0, -300]} scale={[6, 6, 6]} rotation={[0, Math.PI, 0]}>
            <group
                position={[16.014, 0, 3.425]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.01, 0.01, 0.014]}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <RigidBody type="fixed">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube004_column_0.geometry}
                        material={materials.column}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[50, 50, 20]}
                    />
                    </RigidBody>
                </group>
            </group>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane.geometry}
                    material={materials["Material.005"]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={[12.5, 1, 12.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={materials["Material.003"]}
                    position={[0, 5, -12.3]}
                    scale={[12.5, 5, 0.2]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={materials["Material.002"]}
                    position={[-12.509, 5, 0]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[12.5, 5, 0.2]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002.geometry}
                    material={materials["Material.004"]}
                    position={[0, 5, 12.3]}
                    scale={[12.5, 5, 0.2]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane001.geometry}
                    material={nodes.Plane001.material}
                    position={[0, 10, 0]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={[12.5, 1, 12.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005.geometry}
                    material={materials["Material.016"]}
                    position={[-0.209, 5, 9.25]}
                    scale={[12.5, 0.2, 3]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006.geometry}
                    material={materials["Material.014"]}
                    position={[-0.209, 5, -9.25]}
                    scale={[12.5, 0.2, 3]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007.geometry}
                    material={materials["Material.015"]}
                    position={[-9.209, 5, 0.044]}
                    rotation={[0, Math.PI / 2, 0]}
                    scale={[12.4, 0.2, 3]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={materials["Material.017"]}
                    position={[2.78, 7.125, -6.614]}
                    scale={[9.5, 0.1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001.geometry}
                    material={materials["Material.031"]}
                    position={[1.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002.geometry}
                    material={materials["Material.029"]}
                    position={[2.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder003.geometry}
                    material={materials["Material.028"]}
                    position={[2.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004.geometry}
                    material={materials["Material.027"]}
                    position={[3.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder005.geometry}
                    material={materials["Material.026"]}
                    position={[3.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006.geometry}
                    material={materials["Material.025"]}
                    position={[4.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder007.geometry}
                    material={materials["Material.024"]}
                    position={[4.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder008.geometry}
                    material={materials["Material.023"]}
                    position={[5.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder009.geometry}
                    material={materials["Material.022"]}
                    position={[5.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder010.geometry}
                    material={materials["Material.021"]}
                    position={[6.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder011.geometry}
                    material={materials["Material.020"]}
                    position={[6.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder012.geometry}
                    material={materials["Material.019"]}
                    position={[7.077, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder013.geometry}
                    material={materials["Material.032"]}
                    position={[1.066, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder014.geometry}
                    material={materials["Material.033"]}
                    position={[0.566, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder015.geometry}
                    material={materials["Material.034"]}
                    position={[0.066, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder016.geometry}
                    material={materials["Material.035"]}
                    position={[-0.434, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder017.geometry}
                    material={materials["Material.036"]}
                    position={[-0.934, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder018.geometry}
                    material={materials["Material.037"]}
                    position={[-1.434, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder019.geometry}
                    material={materials["Material.038"]}
                    position={[-1.934, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder020.geometry}
                    material={materials["Material.039"]}
                    position={[-2.434, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder021.geometry}
                    material={materials["Material.040"]}
                    position={[-2.934, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder022.geometry}
                    material={materials["Material.041"]}
                    position={[-3.434, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder023.geometry}
                    material={materials["Material.042"]}
                    position={[-3.934, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder024.geometry}
                    material={materials["Material.043"]}
                    position={[-5.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder050.geometry}
                    material={materials["Material.070"]}
                    position={[7.577, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder051.geometry}
                    material={materials["Material.071"]}
                    position={[11.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder052.geometry}
                    material={materials["Material.072"]}
                    position={[-4.434, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder053.geometry}
                    material={materials["Material.073"]}
                    position={[-5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder054.geometry}
                    material={materials["Material.074"]}
                    position={[-5.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder055.geometry}
                    material={materials["Material.075"]}
                    position={[-5.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder056.geometry}
                    material={materials["Material.076"]}
                    position={[-5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder057.geometry}
                    material={materials["Material.077"]}
                    position={[-4.434, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder058.geometry}
                    material={materials["Material.078"]}
                    position={[11.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder059.geometry}
                    material={materials["Material.079"]}
                    position={[7.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder060.geometry}
                    material={materials["Material.080"]}
                    position={[-5.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder061.geometry}
                    material={materials["Material.081"]}
                    position={[-3.934, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder062.geometry}
                    material={materials["Material.082"]}
                    position={[-3.434, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder063.geometry}
                    material={materials["Material.083"]}
                    position={[-2.934, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder064.geometry}
                    material={materials["Material.084"]}
                    position={[-2.434, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder065.geometry}
                    material={materials["Material.085"]}
                    position={[-1.934, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder066.geometry}
                    material={materials["Material.086"]}
                    position={[-1.434, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder067.geometry}
                    material={materials["Material.087"]}
                    position={[-0.934, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder068.geometry}
                    material={materials["Material.088"]}
                    position={[-0.434, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder069.geometry}
                    material={materials["Material.089"]}
                    position={[0.066, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder070.geometry}
                    material={materials["Material.090"]}
                    position={[0.566, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder071.geometry}
                    material={materials["Material.091"]}
                    position={[1.066, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder072.geometry}
                    material={materials["Material.092"]}
                    position={[7.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder073.geometry}
                    material={materials["Material.093"]}
                    position={[6.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder074.geometry}
                    material={materials["Material.094"]}
                    position={[6.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder075.geometry}
                    material={materials["Material.095"]}
                    position={[5.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder076.geometry}
                    material={materials["Material.096"]}
                    position={[5.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder077.geometry}
                    material={materials["Material.097"]}
                    position={[4.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder078.geometry}
                    material={materials["Material.098"]}
                    position={[4.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder079.geometry}
                    material={materials["Material.099"]}
                    position={[3.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder080.geometry}
                    material={materials["Material.100"]}
                    position={[3.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder081.geometry}
                    material={materials["Material.101"]}
                    position={[2.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder082.geometry}
                    material={materials["Material.102"]}
                    position={[2.077, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder083.geometry}
                    material={materials["Material.103"]}
                    position={[1.577, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube008.geometry}
                    material={materials["Material.104"]}
                    position={[2.892, 7.13, 6.615]}
                    scale={[9.5, 0.1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder084.geometry}
                    material={materials["Material.106"]}
                    position={[-6.604, 6.15, -6.066]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder085.geometry}
                    material={materials["Material.107"]}
                    position={[-6.567, 6.15, -0.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder086.geometry}
                    material={materials["Material.108"]}
                    position={[-6.57, 6.15, -0.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder087.geometry}
                    material={materials["Material.109"]}
                    position={[-6.573, 6.15, -1.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder088.geometry}
                    material={materials["Material.110"]}
                    position={[-6.577, 6.15, -1.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder089.geometry}
                    material={materials["Material.111"]}
                    position={[-6.58, 6.15, -2.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder090.geometry}
                    material={materials["Material.112"]}
                    position={[-6.583, 6.15, -2.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder091.geometry}
                    material={materials["Material.113"]}
                    position={[-6.586, 6.15, -3.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder092.geometry}
                    material={materials["Material.114"]}
                    position={[-6.589, 6.15, -3.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder093.geometry}
                    material={materials["Material.115"]}
                    position={[-6.592, 6.15, -4.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder094.geometry}
                    material={materials["Material.116"]}
                    position={[-6.595, 6.15, -4.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder095.geometry}
                    material={materials["Material.117"]}
                    position={[-6.598, 6.15, -5.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder096.geometry}
                    material={materials["Material.118"]}
                    position={[-6.601, 6.15, -5.505]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder097.geometry}
                    material={materials["Material.119"]}
                    position={[-6.564, 6.15, 0.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder098.geometry}
                    material={materials["Material.120"]}
                    position={[-6.561, 6.15, 1.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder099.geometry}
                    material={materials["Material.121"]}
                    position={[-6.558, 6.15, 1.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder100.geometry}
                    material={materials["Material.122"]}
                    position={[-6.555, 6.15, 2.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder101.geometry}
                    material={materials["Material.123"]}
                    position={[-6.552, 6.15, 2.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder102.geometry}
                    material={materials["Material.124"]}
                    position={[-6.549, 6.15, 3.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder103.geometry}
                    material={materials["Material.125"]}
                    position={[-6.546, 6.15, 3.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder104.geometry}
                    material={materials["Material.126"]}
                    position={[-6.543, 6.15, 4.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder105.geometry}
                    material={materials["Material.127"]}
                    position={[-6.54, 6.15, 4.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder106.geometry}
                    material={materials["Material.128"]}
                    position={[-6.537, 6.15, 5.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder107.geometry}
                    material={materials["Material.129"]}
                    position={[-6.534, 6.15, 5.506]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder108.geometry}
                    material={materials["Material.130"]}
                    position={[-6.531, 6.15, 6.006]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube009.geometry}
                    material={materials["Material.131"]}
                    position={[-6.567, 7.127, -0.005]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[6.72, 0.1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder109.geometry}
                    material={materials["Material.132"]}
                    position={[-6.312, 6.15, 6.583]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder110.geometry}
                    material={materials["Material.133"]}
                    position={[-5.911, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder111.geometry}
                    material={materials["Material.134"]}
                    position={[-5.988, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder112.geometry}
                    material={materials["Material.135"]}
                    position={[-6.395, 6.15, -6.623]}
                    rotation={[-Math.PI, 1.565, -Math.PI]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004.geometry}
                    material={nodes.Cube004.material}
                    position={[12.31, 5, -7.4]}
                    scale={[0.2, 5, 5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010.geometry}
                    material={materials["Material.007"]}
                    position={[12.31, 5, 7.4]}
                    scale={[0.2, 5, 5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder025.geometry}
                    material={materials["Material.136"]}
                    position={[8, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder026.geometry}
                    material={materials["Material.137"]}
                    position={[8.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder027.geometry}
                    material={materials["Material.138"]}
                    position={[9, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder028.geometry}
                    material={materials["Material.139"]}
                    position={[9.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder029.geometry}
                    material={materials["Material.140"]}
                    position={[10, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder030.geometry}
                    material={materials["Material.141"]}
                    position={[10.5, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder031.geometry}
                    material={materials["Material.142"]}
                    position={[11, 6.125, -6.614]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder032.geometry}
                    material={materials["Material.143"]}
                    position={[8, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder033.geometry}
                    material={materials["Material.144"]}
                    position={[8.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder034.geometry}
                    material={materials["Material.145"]}
                    position={[9, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder035.geometry}
                    material={materials["Material.146"]}
                    position={[9.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder036.geometry}
                    material={materials["Material.147"]}
                    position={[10, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder037.geometry}
                    material={materials["Material.148"]}
                    position={[10.5, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder038.geometry}
                    material={materials["Material.149"]}
                    position={[11, 6.125, 6.615]}
                    scale={[0.1, 1, 0.1]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube011.geometry}
                    material={nodes.Cube011.material}
                    position={[12.31, 7.494, 0]}
                    scale={[0.2, 2.5, 2.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002.geometry}
                    material={materials["Material.150"]}
                    position={[12.55, 7.159, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={[1, 4, 1.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003.geometry}
                    material={materials["Material.151"]}
                    position={[12.55, 1.592, -8.851]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={[1, 4, 1.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane005.geometry}
                    material={materials["Material.153"]}
                    position={[12.55, 1.583, 8.893]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={[1, 4, 1.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube012.geometry}
                    material={materials["Material.154"]}
                    position={[14.419, 4.806, 0]}
                    scale={[2, 0.2, 5]}
                />
            </RigidBody>
                <group
                    position={[16.014, 0, -3.958]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.01, 0.01, 0.014]}
                >
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube004_column_0001.geometry}
                            material={materials["column.001"]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={[50, 50, 20]}
                        />
                    </group>
                </group>
                <group
                    position={[16.014, 0, -0.489]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.01, 0.01, 0.014]}
                >
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <RigidBody type="fixed">
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube004_column_0002.geometry}
                            material={materials["column.002"]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={[50, 50, 20]}
                        />
                        </RigidBody>
                    </group>
                </group>
                <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane004.geometry}
                    material={nodes.Plane004.material}
                    position={[0, 0, -14.5]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-12.5, -1, -2]}
                />
                </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane006.geometry}
                    material={materials.Material}
                    position={[0, 0, 14.5]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-12.5, -1, -2]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane007.geometry}
                    material={materials["Material.006"]}
                    position={[14, 0, 0]}
                    scale={[1.5, 1, 16.5]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane008.geometry}
                    material={materials["Material.001"]}
                    position={[0, 0, -14.529]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-12.5, -1, -2]}
                />
            </RigidBody>
            <group position={[0, 5.409, -16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus_1.geometry}
                    material={materials["Material.009"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus_2.geometry}
                    material={materials["Material.008"]}
                />
            </group>
            <group position={[12.439, 5.409, -13.007]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus001_1.geometry}
                    material={materials["Material.010"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus001_2.geometry}
                    material={materials["Material.011"]}
                />
            </group>
            <group position={[12.439, 5.409, -16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus002_1.geometry}
                    material={materials["Material.012"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus002_2.geometry}
                    material={materials["Material.013"]}
                />
            </group>
            <group position={[-12.447, 5.409, -16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus003_1.geometry}
                    material={materials["Material.018"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus003_2.geometry}
                    material={materials["Material.030"]}
                />
            </group>
            <group position={[-12.447, 5.409, 16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus004_1.geometry}
                    material={materials["Material.044"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus004_2.geometry}
                    material={materials["Material.045"]}
                />
            </group>
            <group position={[0, 5.409, 16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus005_1.geometry}
                    material={materials["Material.046"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus005_2.geometry}
                    material={materials["Material.047"]}
                />
            </group>
            <group position={[12.439, 5.409, 16.489]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus006_1.geometry}
                    material={materials["Material.048"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus006_2.geometry}
                    material={materials["Material.049"]}
                />
            </group>
            <group position={[12.439, 5.409, 13.007]} scale={[0.4, 0.2, 0.4]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus007_1.geometry}
                    material={materials["Material.050"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus007_2.geometry}
                    material={materials["Material.051"]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/assets/achivements building (1).glb");




