import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function TreesBetween2(props) {
  const { nodes, materials } = useGLTF("/assets/TreesBetween2.glb");
  return (
    <>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[0,0,265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-110,0,265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[350,0,265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[240,0,265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[0,0,65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-105,0,65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[325,0,65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[220,0,65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[60,0,135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[360,0,135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-45,0,135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[255,0,135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[60,0,-65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[360,0,-65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-45,0,-65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[255,0,-65]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-105,0,-135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[0,0,-135]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[-105,0,-265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    <group {...props} dispose={null} rotation={[Math.PI/2,0,0]} position={[0,0,-265]} scale={[0.2,0.2,0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.foliage}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.foliage}
      />
    </group>
    </>
  );
}

useGLTF.preload("/assets/TreesBetween2.glb");